In [6]:
with open('diabetes_data.csv') as f:
    df = f.readlines()

print(f"total rows : {len(df)-1}")
print(df[:5])

total rows : 520
['age;gender;polyuria;polydipsia;sudden_weight_loss;weakness;polyphagia;genital_thrush;visual_blurring;itching;irritability;delayed_healing;partial_paresis;muscle_stiffness;alopecia;obesity;class\n', '40;Male;0;1;0;1;0;0;0;1;0;1;0;1;1;1;1\n', '58;Male;0;0;0;1;0;0;1;0;0;0;1;0;1;0;1\n', '41;Male;1;0;0;1;1;0;0;1;0;1;0;1;1;0;1\n', '45;Male;0;0;1;1;1;1;0;1;0;1;0;0;0;0;1\n']


In [18]:
print( df[0].split(';'), end='\n\n' )

new_df = []

for i in range(1, len(df)):
    row = df[i]
    row = row.replace('\n','')
    temp = row.split(';')
    new_df.append(temp)

print(new_df[:5])

['age', 'gender', 'polyuria', 'polydipsia', 'sudden_weight_loss', 'weakness', 'polyphagia', 'genital_thrush', 'visual_blurring', 'itching', 'irritability', 'delayed_healing', 'partial_paresis', 'muscle_stiffness', 'alopecia', 'obesity', 'class\n']

[['40', 'Male', '0', '1', '0', '1', '0', '0', '0', '1', '0', '1', '0', '1', '1', '1', '1'], ['58', 'Male', '0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '1', '0', '1', '0', '1'], ['41', 'Male', '1', '0', '0', '1', '1', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1'], ['45', 'Male', '0', '0', '1', '1', '1', '1', '0', '1', '0', '1', '0', '0', '0', '0', '1'], ['60', 'Male', '1', '1', '1', '1', '1', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1']]


['age', 'gender', 'polyuria', 'polydipsia', 'sudden_weight_loss', 'weakness', 'polyphagia', 'genital_thrush', 'visual_blurring', 'itching', 'irritability', 'delayed_healing', 'partial_paresis', 'muscle_stiffness', 'alopecia', 'obesity', 'class\n']


In [38]:
train_df = []

for i in range(len(new_df)):  # 520

    cat_sex = [0] * 2
    if new_df[i][1] == "Male":
        cat_sex[0] = 1
    else:
        cat_sex[1] = 1
    
    temp = [
        int(new_df[i][0]), int(new_df[i][2]), int(new_df[i][3]), int(new_df[i][4]), int(new_df[i][5]), int(new_df[i][6]),
        int(new_df[i][7]), int(new_df[i][8]), int(new_df[i][9]), int(new_df[i][10]), int(new_df[i][11]), int(new_df[i][12]),
        int(new_df[i][13]), int(new_df[i][14]), int(new_df[i][15])
    ]
    temp.extend(cat_sex)
    temp.append(int(new_df[i][16]))

    train_df.append(temp)
    
    if i<5:
        print(len(temp), temp)

18 [40, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1]
18 [58, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1]
18 [41, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1]
18 [45, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1]
18 [60, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]


In [62]:
train_x = []
train_y = []

for i in range(len(train_df)):
    temp_x = []
    temp_y = []

    temp_y.append(train_df[i][-1])
    temp_x.append(train_df[i][:-1])

    train_x.append(temp_x[0])
    train_y.append(temp_y[0])

    if i<5:
        print(temp_x, temp_y)


[[40, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0]] [1]
[[58, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0]] [1]
[[41, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0]] [1]
[[45, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0]] [1]
[[60, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]] [1]


In [64]:
import numpy as np

train_x, train_y = np.array(train_x), np.array(train_y)

print(train_x.shape)
print(train_x[:4], end='\n\n')
print(train_y.shape)
print(train_y[:4])

(520, 17)
[[40  0  1  0  1  0  0  0  1  0  1  0  1  1  1  1  0]
 [58  0  0  0  1  0  0  1  0  0  0  1  0  1  0  1  0]
 [41  1  0  0  1  1  0  0  1  0  1  0  1  1  0  1  0]
 [45  0  0  1  1  1  1  0  1  0  1  0  0  0  0  1  0]]

(520,)
[1 1 1 1]


(17,)

In [71]:
import tensorflow as tf
from tensorflow.keras import layers

model = tf.keras.models.Sequential([

    layers.Input( shape = train_x.shape[1:] ),

    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')

])

model.compile(
    loss = 'binary_crossentropy',
    optimizer = 'adam',
    metrics = ['accuracy']
)

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 64)                1152      
                                                                 
 dense_7 (Dense)             (None, 32)                2080      
                                                                 
 dense_8 (Dense)             (None, 1)                 33        
                                                                 
Total params: 3,265
Trainable params: 3,265
Non-trainable params: 0
_________________________________________________________________


In [74]:
model.fit(
    train_x[:400], train_y[:400],
    epochs = 60,
    validation_data = (train_x[400:], train_y[400:])
)

Epoch 1/60
13/13 [==============================] - 0s 40ms/step - loss: 0.1843 - accuracy: 0.9375 - val_loss: 0.1025 - val_accuracy: 0.9667
Epoch 2/60
13/13 [==============================] - 0s 10ms/step - loss: 0.1737 - accuracy: 0.9325 - val_loss: 0.1100 - val_accuracy: 0.9667
Epoch 3/60
13/13 [==============================] - 0s 10ms/step - loss: 0.1725 - accuracy: 0.9275 - val_loss: 0.1125 - val_accuracy: 0.9667
Epoch 4/60
13/13 [==============================] - 0s 9ms/step - loss: 0.1710 - accuracy: 0.9325 - val_loss: 0.1059 - val_accuracy: 0.9667
Epoch 5/60
13/13 [==============================] - 0s 9ms/step - loss: 0.1700 - accuracy: 0.9275 - val_loss: 0.1034 - val_accuracy: 0.9667
Epoch 6/60
13/13 [==============================] - 0s 10ms/step - loss: 0.1718 - accuracy: 0.9275 - val_loss: 0.1131 - val_accuracy: 0.9667
Epoch 7/60
13/13 [==============================] - 0s 11ms/step - loss: 0.1722 - accuracy: 0.9300 - val_loss: 0.1068 - val_accuracy: 0.9667
Epoch 8/60
13/1